export const DEVICE_COLOR_MAP = new Map();
DEVICE_COLOR_MAP.set(0,  "#8DAAF7"); // SPG
DEVICE_COLOR_MAP.set(1,  "#A87AF7"); // NPG

DEVICE_COLOR_MAP.set(2,  "#708238"); // FE HARV
DEVICE_COLOR_MAP.set(7,  "#93C572"); // FE REFN

DEVICE_COLOR_MAP.set(3,  "#893439"); // AL HARV
DEVICE_COLOR_MAP.set(8,  "#D96767"); // AL REFN

DEVICE_COLOR_MAP.set(4,  "#F18C62"); // CU HARV
DEVICE_COLOR_MAP.set(9,  "#FFB57E"); // CU REFN

DEVICE_COLOR_MAP.set(5,  "#75ABCF"); // SI HARV
DEVICE_COLOR_MAP.set(10, "#ADC2D3"); // SI REFN

DEVICE_COLOR_MAP.set(6,  "#E4A2AB"); // PU HARV
DEVICE_COLOR_MAP.set(11, "#EDCEDB"); // PEF

DEVICE_COLOR_MAP.set(12, "#9FACA3"); // UTB
DEVICE_COLOR_MAP.set(13, "#88D4CA"); // UTL
DEVICE_COLOR_MAP.set(14, "#FFDD8D"); // UPSF
DEVICE_COLOR_MAP.set(15, "#DF90FF"); // NDPE