export const DEVICE_TYPE_MAP = new Map();
DEVICE_TYPE_MAP.set(0,  "SPG");
DEVICE_TYPE_MAP.set(1,  "NPG");
DEVICE_TYPE_MAP.set(2,  "FE Harvester");
DEVICE_TYPE_MAP.set(3,  "AL Harvester");
DEVICE_TYPE_MAP.set(4,  "CU Harvester");
DEVICE_TYPE_MAP.set(5,  "SI Harvester");
DEVICE_TYPE_MAP.set(6,  "PU Harvester");
DEVICE_TYPE_MAP.set(7,  "FE Refinery");
DEVICE_TYPE_MAP.set(8,  "AL Refinery");
DEVICE_TYPE_MAP.set(9,  "CU Refinery");
DEVICE_TYPE_MAP.set(10, "SI Refinery");
DEVICE_TYPE_MAP.set(11, "PEF");
DEVICE_TYPE_MAP.set(12, "UTB");
DEVICE_TYPE_MAP.set(13, "UTL");
DEVICE_TYPE_MAP.set(14, "UPSF");
DEVICE_TYPE_MAP.set(15, "NDPE");